site_name: MIMOSA documentation

nav:
  - Home: index.md
  - Model documentation:
      - General structure: components/general.md
      - Components:
          - Economics: components/economics.md
          - Emissions: components/emissions.md
  - Parameter reference: parameters.md
  - Installing MIMOSA: installation.md
  - Running MIMOSA: run.md
  - Extending MIMOSA: extending_mimosa.md
  - Model code: "https://github.com/kvanderwijst/MIMOSA"

repo_url: https://github.com/kvanderwijst/MIMOSA

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  favicon: assets/circle_logo.svg
  logo: assets/circle_logo.svg
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.expand

watch:
  - mimosa

hooks:
  - mkdocs_hooks.py

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
          paths: [src]
  - search
  - open-in-new-tab

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
