site_name: MIMOSA documentation

theme:
  name: material
  palette:
    primary: light green
  favicon: assets/circle_logo.svg
  logo: assets/circle_logo.svg

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
  - search
  - open-in-new-tab

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - mimosa

hooks:
  - mkdocs_hooks.py

nav:
  - Home: index.md
  - Installing and running MIMOSA: usage.md
  - Model components:
      - Economics: components/economics.md
      - Emissions: components/emissions.md
  - Parameter reference: parameters.md
  - Extending MIMOSA: extending_mimosa.md
  - Model code: "https://github.com/kvanderwijst/MIMOSA"
