regionstype: IMAGE26
regions:
  CAN:
  USA:
  MEX:
  RCAM:
  BRA:
  RSAM:
  NAF:
  WAF:
  EAF:
  SAF:
  WEU:
  CEU:
  TUR:
  UKR:
  STAN:
  RUS:
  ME:
  INDIA:
  KOR:
  CHN:
  SEAS:
  INDO:
  JAP:
  OCE:
  RSAS:
  RSAF:

input:
  db_filename: inputdata/data/data_IMAGE_SSP.csv
  # db_filename: ../../Databases/SSP_IAM_V2_201811.csv
  baselines:
    SSP1:
      scenario: SSP1-Ref-SPA0-V17
      model: IMAGE
    SSP2:
      scenario: SSP2-Ref-SPA0-V17
      model: IMAGE
    SSP3:
      scenario: SSP3-Ref-SPA0-V17
      model: IMAGE
    SSP4:
      scenario: SSP4-Ref-SPA0-V17
      model: IMAGE
    SSP5:
      scenario: SSP5-Ref-SPA0-V17
      model: IMAGE

  variables:
    GDP: GDP|PPP
    emissions: Emissions|CO2
    population: Population

time:
  start: 2020
  end: 2125
  dt: 1

SSP: "SSP2"

economics:
  PRTP: 0.015
  elasmu: 1.45
  GDP:
    alpha: 0.3
    depreciation of capital: 0.05
    savings rate: 0.21
  MAC:
    beta: 2
    rho: 0.82
    gamma: 2442 USD2005/tCO2
  damages:
    percentage reversible: 1
    scale factor: 1
    ignore damages: False
    quantile: 0.5 # Only used for COACCH
    coacch_slr_withadapt: True # Only used for COACCH
  adaptation:
    curr_level: 0
    fixed: False

emissions:
  carbonbudget: 800 GtCO2 # False or a quantity
  global min level: -20 GtCO2/yr # False or a quantity
  regional min level: -10 GtCO2/yr # False or a quantity
  not positive after budget year: True
  baseline carbon intensity: True
  inertia:
    global: False # False or a number < 0, % of initial emissions
    regional: -0.05 # False or a number < 0, % of initial emissions

temperature:
  initial: 1.096224 delta_degC
  TCRE: 0.62 delta_degC/(TtCO2)

default units:
  currency_unit: trillion USD2005/yr
  emissionsrate_unit: emissions_unit/yr
  emissions_unit: Gt CO2
  temperature_unit: delta_degC
  population_unit: billion

model:
  damage module: RICE2012 # RICE2010, RICE2012 or WITCH
  objective module: utility # utility or globalcosts
  allow trade: True
