SSP: "SSP5"

economics:
  PRTP: 0.001
  elasmu: 1.45
  GDP:
    alpha: 0.3
    depreciation of capital: 0.05
    savings rate: 0.21
  MAC:
    beta: 2
    rho: 0.82
    gamma: 24420000000 USD2005/tCO2
  damages:
    percentage reversible: 1
    scale factor: 1
    ignore damages: False
    quantile: 0.5 # Only used for COACCH
    coacch_slr_withadapt: True # Only used for COACCH
  adaptation:
    curr_level: 0
    fixed: False
